services:
  mssql:
    container_name: mssqldatabase
    restart: always
    environment: 
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Mssqn.123
    image: mcr.microsoft.com/mssql/server
    ports:
    - 1433:1433
  authusers:
    container_name: authuaserapp
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: 
    - ./.env
    ports:
     - 3000:3000
    depends_on:
     - mssql